name: TheStafferEmployee
description: TheStaffer Employees App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  rxdart: ^0.27.3
  equatable: ^2.0.3
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  introduction_screen: ^3.0.0
  flutter_svg: ^1.0.3
  eva_icons_flutter: ^3.1.0
  adobe_xd: ^2.0.1
  intro_views_flutter: ^3.2.0
  rounded_expansion_tile: 0.0.13 
  intl: ^0.19.0
  carousel_slider: ^4.2.1 
  http: ^1.2.0
  avatar_view: ^1.0.0+3
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.20
  slide_digital_clock: ^1.0.2
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2
  flutter_lints:
 

dev_dependencies:
  flutter_app_name: ^0.1.1
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "TheStafferEmployee"
flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconsss.png"  


flutter:


  uses-material-design: true

  assets:
    - images/

